// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models;

namespace WebApplication3.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211012113545_Initwww2")]
    partial class Initwww2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.Models.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WebApplication3.Models.Peremeshenie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data_demontazha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_ustanivki")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_pomeshenie")
                        .HasColumnType("int");

                    b.Property<int>("id_technika")
                        .HasColumnType("int");

                    b.Property<int?>("pomeshenieid")
                        .HasColumnType("int");

                    b.Property<string>("prichina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("technikaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pomeshenieid");

                    b.HasIndex("technikaid");

                    b.ToTable("Peremeshenies");
                });

            modelBuilder.Entity("WebApplication3.Models.Pomeshenie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("etazh")
                        .HasColumnType("int");

                    b.Property<string>("gorod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kab_nom")
                        .HasColumnType("int");

                    b.Property<string>("ulitsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("zdanie_nom")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Pomeshenies");
                });

            modelBuilder.Entity("WebApplication3.Models.Rashod_material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data_demontazha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_ustanivki")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_material")
                        .HasColumnType("int");

                    b.Property<int?>("materialid")
                        .HasColumnType("int");

                    b.Property<string>("prichina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("materialid");

                    b.ToTable("Rashod_Materials");
                });

            modelBuilder.Entity("WebApplication3.Models.Sotrudniki", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dolzhnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("i")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("o")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sotrudnikis");
                });

            modelBuilder.Entity("WebApplication3.Models.Technika", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_pomeshenie")
                        .HasColumnType("int");

                    b.Property<int>("id_sotrudnik")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pomeshenieid")
                        .HasColumnType("int");

                    b.Property<int?>("sotrudnikiid")
                        .HasColumnType("int");

                    b.Property<string>("tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("pomeshenieid");

                    b.HasIndex("sotrudnikiid");

                    b.ToTable("Technikas");
                });

            modelBuilder.Entity("WebApplication3.Models.Peremeshenie", b =>
                {
                    b.HasOne("WebApplication3.Models.Pomeshenie", "pomeshenie")
                        .WithMany()
                        .HasForeignKey("pomeshenieid");

                    b.HasOne("WebApplication3.Models.Technika", "technika")
                        .WithMany()
                        .HasForeignKey("technikaid");

                    b.Navigation("pomeshenie");

                    b.Navigation("technika");
                });

            modelBuilder.Entity("WebApplication3.Models.Rashod_material", b =>
                {
                    b.HasOne("WebApplication3.Models.Material", "material")
                        .WithMany()
                        .HasForeignKey("materialid");

                    b.Navigation("material");
                });

            modelBuilder.Entity("WebApplication3.Models.Technika", b =>
                {
                    b.HasOne("WebApplication3.Models.Pomeshenie", "pomeshenie")
                        .WithMany()
                        .HasForeignKey("pomeshenieid");

                    b.HasOne("WebApplication3.Models.Sotrudniki", "sotrudniki")
                        .WithMany()
                        .HasForeignKey("sotrudnikiid");

                    b.Navigation("pomeshenie");

                    b.Navigation("sotrudniki");
                });
#pragma warning restore 612, 618
        }
    }
}
